version: "3.9"
services:
  backend:
    build: ./backend
    container_name: calc-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build: 
        context: ./frontend
        args:
          - REACT_APP_API_URL=http://localhost:8080
    container_name: calc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge